# Generated by Django 4.0.4 on 2022-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='models/default.jpg', upload_to='static/images/'),
        ),
    ]
